load("@rules_cc//cc:defs.bzl", "cc_binary")

# build one simple print message function
cc_binary(
    name = "cout",
    srcs = ["cout.cpp"],
)

# build char function
cc_binary(
    name = "char",
    srcs = ["char.cpp"],
)

# build pointer function
cc_binary(
    name = "pointer",
    srcs = ["pointer.cpp"],
)